# Generated by Django 4.0.1 on 2022-01-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_category_level_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('1', '1')], max_length=200, null=True),
        ),
    ]
