# Generated by Django 4.0.1 on 2022-01-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_brand_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('1', '1')], max_length=200, null=True),
        ),
    ]
