# Generated by Django 4.0.1 on 2022-01-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_category_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=200, null=True),
        ),
    ]
