# Generated by Django 4.0.1 on 2022-01-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_category_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.CharField(choices=[('2', '2'), ('1', '1'), ('3', '3')], max_length=200, null=True),
        ),
    ]
