# Generated by Django 3.2 on 2022-01-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220113_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(blank=True, choices=[(8, 'Xorazm'), (12, 'Buxoro'), (1, 'Toshkent:'), (5, 'Navoi'), (4, 'Namangan'), (6, 'Samarqand'), (11, 'Toshkent vil'), (9, 'Fargona'), (3, 'Andijon'), (7, 'Qashqadaryo'), (10, 'Jizzax'), (2, 'Surxondaryo')], max_length=100),
        ),
    ]
