# Generated by Django 3.2 on 2022-01-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_address_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(blank=True, choices=[(4, 'Namangan'), (8, 'Xorazm'), (9, 'Fargona'), (1, 'Toshkent:'), (6, 'Samarqand'), (12, 'Buxoro'), (3, 'Andijon'), (5, 'Navoi'), (10, 'Jizzax'), (11, 'Toshkent vil'), (2, 'Surxondaryo'), (7, 'Qashqadaryo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
    ]
