# Generated by Django 3.2 on 2022-01-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_address_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Toshkent', 'Toshkent:'), ('Samarqand', 'Samarqand'), ('Surxondaryo', 'Surxondaryo'), ('Andijon', 'Andijon'), ('Qashqadaryo', 'Qashqadaryo'), ('Namangan', 'Namangan'), ('Navoi', 'Navoi'), ('Xorazm', 'Xorazm')], default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=50, null=True),
        ),
    ]
