# Generated by Django 3.2 on 2022-01-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220113_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Samarqand', 'Samarqand'), ('Surxondaryo', 'Surxondaryo'), ('Navoi', 'Navoi'), ('Qashqadaryo', 'Qashqadaryo'), ('Andijon', 'Andijon'), ('Xorazm', 'Xorazm'), ('Toshkent', 'Toshkent:'), ('Namangan', 'Namangan')], default='empty', max_length=100),
        ),
    ]
