# Generated by Django 3.2 on 2022-01-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_address_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Toshkent', 'Toshkent:'), ('Namangan', 'Namangan'), ('Surxondaryo', 'Surxondaryo'), ('Andijon', 'Andijon'), ('Qashqadaryo', 'Qashqadaryo'), ('Samarqand', 'Samarqand'), ('Xorazm', 'Xorazm'), ('Navoi', 'Navoi')], default='empty', max_length=100),
        ),
    ]
