# Generated by Django 3.2 on 2022-01-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220113_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Andijon', 'Andijon'), ('Toshkent', 'Toshkent:'), ('Navoi', 'Navoi'), ('Xorazm', 'Xorazm'), ('Surxondaryo', 'Surxondaryo'), ('Namangan', 'Namangan'), ('Qashqadaryo', 'Qashqadaryo'), ('Samarqand', 'Samarqand')], default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=50, null=True),
        ),
    ]
