# Generated by Django 3.2 on 2022-01-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_address_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Surxondaryo', 'Surxondaryo'), ('Toshkent', 'Toshkent:'), ('Andijon', 'Andijon'), ('Qashqadaryo', 'Qashqadaryo'), ('Navoi', 'Navoi'), ('Samarqand', 'Samarqand'), ('Xorazm', 'Xorazm'), ('Namangan', 'Namangan')], default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
    ]
