# Generated by Django 3.2 on 2022-01-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220113_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Samarqand', 'Samarqand'), ('Navoi', 'Navoi'), ('Xorazm', 'Xorazm'), ('Surxondaryo', 'Surxondaryo'), ('Namangan', 'Namangan'), ('Qashqadaryo', 'Qashqadaryo'), ('Andijon', 'Andijon'), ('Toshkent', 'Toshkent:')], default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=50, null=True),
        ),
    ]
