# Generated by Django 4.0.1 on 2022-01-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20220113_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Andijon', 'Andijon'), ('Qashqadaryo', 'Qashqadaryo'), ('Namangan', 'Namangan'), ('Toshkent', 'Toshkent:'), ('Xorazm', 'Xorazm'), ('Surxondaryo', 'Surxondaryo'), ('Navoi', 'Navoi'), ('Samarqand', 'Samarqand')], default='empty', max_length=100),
        ),
    ]
