# Generated by Django 4.0.1 on 2022-01-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_address_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Namangan', 'Namangan'), ('Surxondaryo', 'Surxondaryo'), ('Andijon', 'Andijon'), ('Samarqand', 'Samarqand'), ('Qashqadaryo', 'Qashqadaryo'), ('Toshkent', 'Toshkent:'), ('Navoi', 'Navoi'), ('Xorazm', 'Xorazm')], default='empty', max_length=100),
        ),
    ]
