# Generated by Django 3.2 on 2022-01-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_address_region_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Fargona', 'Fargona'), ('Toshkent vil', 'Toshkent vil'), ('Samarqand', 'Samarqand'), ('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ('Jizzax', 'Jizzax'), ('Toshkent', 'Toshkent:'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxondaryo', 'Surxondaryo'), ('Navoi', 'Navoi'), ('Xorazm', 'Xorazm'), ('Namangan', 'Namangan')], default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=50, null=True),
        ),
    ]
