# Generated by Django 3.2 on 2022-01-14 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20220113_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Surxondaryo', 'Surxondaryo'), ('Toshkent vil', 'Toshkent vil'), ('Navoi', 'Navoi'), ('Fargona', 'Fargona'), ('Toshkent', 'Toshkent:'), ('Qashqadaryo', 'Qashqadaryo'), ('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ('Xorazm', 'Xorazm'), ('Jizzax', 'Jizzax'), ('Samarqand', 'Samarqand'), ('Namangan', 'Namangan')], default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
