# Generated by Django 3.2 on 2022-01-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20220114_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Samarqand', 'Samarqand'), ('Andijon', 'Andijon'), ('Fargona', 'Fargona'), ('Xorazm', 'Xorazm'), ('Surxondaryo', 'Surxondaryo'), ('Navoi', 'Navoi'), ('Jizzax', 'Jizzax'), ('Namangan', 'Namangan'), ('Buxoro', 'Buxoro'), ('Qashqadaryo', 'Qashqadaryo'), ('Toshkent vil', 'Toshkent vil'), ('Toshkent', 'Toshkent:')], default='empty', max_length=100),
        ),
    ]
