# Generated by Django 4.0.1 on 2022-01-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_address_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Toshkent vil', 'Toshkent vil'), ('Samarqand', 'Samarqand'), ('Buxoro', 'Buxoro'), ('Andijon', 'Andijon'), ('Toshkent', 'Toshkent:'), ('Fargona', 'Fargona'), ('Xorazm', 'Xorazm'), ('Surxondaryo', 'Surxondaryo'), ('Jizzax', 'Jizzax'), ('Navoi', 'Navoi'), ('Namangan', 'Namangan'), ('Qashqadaryo', 'Qashqadaryo')], default='empty', max_length=100),
        ),
    ]
