# Generated by Django 4.0.1 on 2022-01-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_profile_name_alter_address_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Xorazm', 'Xorazm'), ('Toshkent', 'Toshkent:'), ('Toshkent vil', 'Toshkent vil'), ('Navoi', 'Navoi'), ('Surxondaryo', 'Surxondaryo'), ('Fargona', 'Fargona'), ('Namangan', 'Namangan'), ('Buxoro', 'Buxoro'), ('Samarqand', 'Samarqand'), ('Andijon', 'Andijon'), ('Jizzax', 'Jizzax'), ('Qashqadaryo', 'Qashqadaryo')], default='empty', max_length=100),
        ),
    ]
