# Generated by Django 4.0.1 on 2022-01-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_address_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Namangan', 'Namangan'), ('Toshkent vil', 'Toshkent vil'), ('Qashqadaryo', 'Qashqadaryo'), ('Andijon', 'Andijon'), ('Xorazm', 'Xorazm'), ('Buxoro', 'Buxoro'), ('Navoi', 'Navoi'), ('Samarqand', 'Samarqand'), ('Surxondaryo', 'Surxondaryo'), ('Fargona', 'Fargona'), ('Jizzax', 'Jizzax'), ('Toshkent', 'Toshkent:')], default='empty', max_length=100),
        ),
    ]
