# Generated by Django 4.0.1 on 2022-01-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_address_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Fargona', 'Fargona'), ('Jizzax', 'Jizzax'), ('Xorazm', 'Xorazm'), ('Navoi', 'Navoi'), ('Toshkent vil', 'Toshkent vil'), ('Buxoro', 'Buxoro'), ('Toshkent', 'Toshkent:'), ('Surxondaryo', 'Surxondaryo'), ('Qashqadaryo', 'Qashqadaryo'), ('Samarqand', 'Samarqand'), ('Namangan', 'Namangan'), ('Andijon', 'Andijon')], default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
    ]
