# Generated by Django 4.0.1 on 2022-01-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_address_region_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Jizzax', 'Jizzax'), ('Toshkent', 'Toshkent:'), ('Buxoro', 'Buxoro'), ('Qashqadaryo', 'Qashqadaryo'), ('Xorazm', 'Xorazm'), ('Navoi', 'Navoi'), ('Andijon', 'Andijon'), ('Fargona', 'Fargona'), ('Surxondaryo', 'Surxondaryo'), ('Samarqand', 'Samarqand'), ('Toshkent vil', 'Toshkent vil'), ('Namangan', 'Namangan')], default='empty', max_length=100),
        ),
    ]
