# Generated by Django 4.0.1 on 2022-01-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_address_region_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Navoi', 'Navoi'), ('Toshkent', 'Toshkent:'), ('Qashqadaryo', 'Qashqadaryo'), ('Samarqand', 'Samarqand'), ('Jizzax', 'Jizzax'), ('Surxondaryo', 'Surxondaryo'), ('Andijon', 'Andijon'), ('Namangan', 'Namangan'), ('Xorazm', 'Xorazm'), ('Toshkent vil', 'Toshkent vil'), ('Buxoro', 'Buxoro'), ('Fargona', 'Fargona')], default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
    ]
