# Generated by Django 4.0.1 on 2022-01-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_address_region_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Xorazm', 'Xorazm'), ('Navoi', 'Navoi'), ('Namangan', 'Namangan'), ('Samarqand', 'Samarqand'), ('Toshkent', 'Toshkent:'), ('Toshkent vil', 'Toshkent vil'), ('Buxoro', 'Buxoro'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxondaryo', 'Surxondaryo'), ('Andijon', 'Andijon'), ('Fargona', 'Fargona'), ('Jizzax', 'Jizzax')], default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=50, null=True),
        ),
    ]
