# Generated by Django 4.0.1 on 2022-01-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_address_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Buxoro', 'Buxoro'), ('Navoi', 'Navoi'), ('Samarqand', 'Samarqand'), ('Toshkent vil', 'Toshkent vil'), ('Xorazm', 'Xorazm'), ('Qashqadaryo', 'Qashqadaryo'), ('Namangan', 'Namangan'), ('Fargona', 'Fargona'), ('Toshkent', 'Toshkent:'), ('Jizzax', 'Jizzax'), ('Surxondaryo', 'Surxondaryo'), ('Andijon', 'Andijon')], default='empty', max_length=100),
        ),
    ]
