# Generated by Django 4.0.1 on 2022-01-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_address_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Toshkent vil', 'Toshkent vil'), ('Fargona', 'Fargona'), ('Buxoro', 'Buxoro'), ('Samarqand', 'Samarqand'), ('Andijon', 'Andijon'), ('Jizzax', 'Jizzax'), ('Qashqadaryo', 'Qashqadaryo'), ('Toshkent', 'Toshkent:'), ('Xorazm', 'Xorazm'), ('Namangan', 'Namangan'), ('Navoi', 'Navoi'), ('Surxondaryo', 'Surxondaryo')], default='empty', max_length=100),
        ),
    ]
