# Generated by Django 4.0.1 on 2022-01-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_address_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Toshkent', 'Toshkent:'), ('Samarqand', 'Samarqand'), ('Namangan', 'Namangan'), ('Xorazm', 'Xorazm'), ('Toshkent vil', 'Toshkent vil'), ('Qashqadaryo', 'Qashqadaryo'), ('Andijon', 'Andijon'), ('Jizzax', 'Jizzax'), ('Navoi', 'Navoi'), ('Buxoro', 'Buxoro'), ('Fargona', 'Fargona'), ('Surxondaryo', 'Surxondaryo')], default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=50, null=True),
        ),
    ]
