# Generated by Django 4.0.1 on 2022-01-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_address_region_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Toshkent', 'Toshkent:'), ('Surxondaryo', 'Surxondaryo'), ('Qashqadaryo', 'Qashqadaryo'), ('Namangan', 'Namangan'), ('Samarqand', 'Samarqand'), ('Jizzax', 'Jizzax'), ('Xorazm', 'Xorazm'), ('Toshkent vil', 'Toshkent vil'), ('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ('Fargona', 'Fargona'), ('Navoi', 'Navoi')], default='empty', max_length=100),
        ),
    ]
