# Generated by Django 4.0.1 on 2022-01-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_address_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Jizzax', 'Jizzax'), ('Andijon', 'Andijon'), ('Navoi', 'Navoi'), ('Toshkent vil', 'Toshkent vil'), ('Buxoro', 'Buxoro'), ('Fargona', 'Fargona'), ('Samarqand', 'Samarqand'), ('Qashqadaryo', 'Qashqadaryo'), ('Xorazm', 'Xorazm'), ('Surxondaryo', 'Surxondaryo'), ('Namangan', 'Namangan'), ('Toshkent', 'Toshkent:')], default='empty', max_length=100),
        ),
    ]
