# Generated by Django 4.0.1 on 2022-01-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_address_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Surxondaryo', 'Surxondaryo'), ('Xorazm', 'Xorazm'), ('Toshkent vil', 'Toshkent vil'), ('Toshkent', 'Toshkent:'), ('Andijon', 'Andijon'), ('Namangan', 'Namangan'), ('Navoi', 'Navoi'), ('Fargona', 'Fargona'), ('Qashqadaryo', 'Qashqadaryo'), ('Buxoro', 'Buxoro'), ('Jizzax', 'Jizzax'), ('Samarqand', 'Samarqand')], default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
    ]
