# Generated by Django 4.0.1 on 2022-01-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_address_region_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Samarqand', 'Samarqand'), ('Surxondaryo', 'Surxondaryo'), ('Qashqadaryo', 'Qashqadaryo'), ('Navoi', 'Navoi'), ('Andijon', 'Andijon'), ('Xorazm', 'Xorazm'), ('Jizzax', 'Jizzax'), ('Toshkent vil', 'Toshkent vil'), ('Fargona', 'Fargona'), ('Namangan', 'Namangan'), ('Toshkent', 'Toshkent:'), ('Buxoro', 'Buxoro')], default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
    ]
