# Generated by Django 4.0.1 on 2022-01-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_address_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Toshkent vil', 'Toshkent vil'), ('Toshkent', 'Toshkent:'), ('Andijon', 'Andijon'), ('Jizzax', 'Jizzax'), ('Samarqand', 'Samarqand'), ('Navoi', 'Navoi'), ('Surxondaryo', 'Surxondaryo'), ('Fargona', 'Fargona'), ('Xorazm', 'Xorazm'), ('Buxoro', 'Buxoro'), ('Qashqadaryo', 'Qashqadaryo'), ('Namangan', 'Namangan')], default='empty', max_length=100),
        ),
    ]
