# Generated by Django 4.0.1 on 2022-01-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_remove_baseuser_date_created_alter_address_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Toshkent', 'Toshkent:'), ('Toshkent vil', 'Toshkent vil'), ('Xorazm', 'Xorazm'), ('Qashqadaryo', 'Qashqadaryo'), ('Buxoro', 'Buxoro'), ('Andijon', 'Andijon'), ('Jizzax', 'Jizzax'), ('Namangan', 'Namangan'), ('Fargona', 'Fargona'), ('Surxondaryo', 'Surxondaryo'), ('Navoi', 'Navoi'), ('Samarqand', 'Samarqand')], default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=50, null=True),
        ),
    ]
