# Generated by Django 4.0.1 on 2022-01-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_address_region_alter_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Toshkent', 'Toshkent:'), ('Andijon', 'Andijon'), ('Toshkent vil', 'Toshkent vil'), ('Buxoro', 'Buxoro'), ('Surxondaryo', 'Surxondaryo'), ('Navoi', 'Navoi'), ('Samarqand', 'Samarqand'), ('Fargona', 'Fargona'), ('Xorazm', 'Xorazm'), ('Namangan', 'Namangan'), ('Qashqadaryo', 'Qashqadaryo'), ('Jizzax', 'Jizzax')], default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
    ]
