# Generated by Django 4.0.1 on 2022-01-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_address_region_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Navoi', 'Navoi'), ('Samarqand', 'Samarqand'), ('Namangan', 'Namangan'), ('Jizzax', 'Jizzax'), ('Toshkent', 'Toshkent:'), ('Qashqadaryo', 'Qashqadaryo'), ('Xorazm', 'Xorazm'), ('Fargona', 'Fargona'), ('Toshkent vil', 'Toshkent vil'), ('Buxoro', 'Buxoro'), ('Surxondaryo', 'Surxondaryo'), ('Andijon', 'Andijon')], default='empty', max_length=100),
        ),
    ]
