# Generated by Django 4.0.1 on 2022-01-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_baseuser_date_created_alter_address_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Jizzax', 'Jizzax'), ('Xorazm', 'Xorazm'), ('Toshkent vil', 'Toshkent vil'), ('Navoi', 'Navoi'), ('Buxoro', 'Buxoro'), ('Andijon', 'Andijon'), ('Qashqadaryo', 'Qashqadaryo'), ('Namangan', 'Namangan'), ('Fargona', 'Fargona'), ('Toshkent', 'Toshkent:'), ('Samarqand', 'Samarqand'), ('Surxondaryo', 'Surxondaryo')], default='empty', max_length=100),
        ),
    ]
