# Generated by Django 4.0.1 on 2022-01-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_address_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Andijon', 'Andijon'), ('Surxondaryo', 'Surxondaryo'), ('Samarqand', 'Samarqand'), ('Navoi', 'Navoi'), ('Namangan', 'Namangan'), ('Toshkent', 'Toshkent:'), ('Toshkent vil', 'Toshkent vil'), ('Xorazm', 'Xorazm'), ('Qashqadaryo', 'Qashqadaryo'), ('Fargona', 'Fargona'), ('Buxoro', 'Buxoro'), ('Jizzax', 'Jizzax')], default='empty', max_length=100),
        ),
    ]
