# Generated by Django 4.0.1 on 2022-01-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_address_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Qashqadaryo', 'Qashqadaryo'), ('Namangan', 'Namangan'), ('Navoi', 'Navoi'), ('Fargona', 'Fargona'), ('Xorazm', 'Xorazm'), ('Toshkent vil', 'Toshkent vil'), ('Samarqand', 'Samarqand'), ('Toshkent', 'Toshkent:'), ('Buxoro', 'Buxoro'), ('Jizzax', 'Jizzax'), ('Andijon', 'Andijon'), ('Surxondaryo', 'Surxondaryo')], default='empty', max_length=100),
        ),
    ]
