# Generated by Django 4.0.1 on 2022-01-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_address_region_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Navoi', 'Navoi'), ('Andijon', 'Andijon'), ('Fargona', 'Fargona'), ('Surxondaryo', 'Surxondaryo'), ('Namangan', 'Namangan'), ('Jizzax', 'Jizzax'), ('Toshkent', 'Toshkent:'), ('Samarqand', 'Samarqand'), ('Toshkent vil', 'Toshkent vil'), ('Xorazm', 'Xorazm'), ('Buxoro', 'Buxoro'), ('Qashqadaryo', 'Qashqadaryo')], default='empty', max_length=100),
        ),
    ]
