# Generated by Django 4.0.1 on 2022-01-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_alter_address_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Toshkent vil', 'Toshkent vil'), ('Andijon', 'Andijon'), ('Toshkent', 'Toshkent:'), ('Navoi', 'Navoi'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxondaryo', 'Surxondaryo'), ('Buxoro', 'Buxoro'), ('Jizzax', 'Jizzax'), ('Fargona', 'Fargona'), ('Namangan', 'Namangan'), ('Xorazm', 'Xorazm'), ('Samarqand', 'Samarqand')], default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
    ]
