# Generated by Django 4.0.1 on 2022-01-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_alter_address_region_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Jizzax', 'Jizzax'), ('Navoi', 'Navoi'), ('Qashqadaryo', 'Qashqadaryo'), ('Toshkent vil', 'Toshkent vil'), ('Surxondaryo', 'Surxondaryo'), ('Fargona', 'Fargona'), ('Samarqand', 'Samarqand'), ('Xorazm', 'Xorazm'), ('Namangan', 'Namangan'), ('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ('Toshkent', 'Toshkent:')], default='empty', max_length=100),
        ),
    ]
