# Generated by Django 4.0.1 on 2022-01-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_alter_address_region_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Toshkent', 'Toshkent:'), ('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ('Namangan', 'Namangan'), ('Fargona', 'Fargona'), ('Samarqand', 'Samarqand'), ('Jizzax', 'Jizzax'), ('Toshkent vil', 'Toshkent vil'), ('Xorazm', 'Xorazm'), ('Navoi', 'Navoi'), ('Surxondaryo', 'Surxondaryo'), ('Qashqadaryo', 'Qashqadaryo')], default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
    ]
