# Generated by Django 4.0.1 on 2022-01-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_cart_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='compelted',
            field=models.BooleanField(default=False),
        ),
    ]
