# Generated by Django 4.0.1 on 2022-01-15 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_cart_compelted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='compelted',
            new_name='completed',
        ),
    ]
