# Generated by Django 4.0.1 on 2022-01-17 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_address_region'),
        ('order', '0003_order_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_address', to='accounts.address'),
        ),
    ]
