# Generated by Django 4.0.1 on 2022-01-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Delivered', 'Delivered'), ('Delivering', 'Delivering')], max_length=100, null=True),
        ),
    ]
