# Generated by Django 4.0.1 on 2022-01-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Received', 'Received'), ('Shipped', 'Shipped')], max_length=100, null=True),
        ),
    ]
