# Generated by Django 4.0.1 on 2022-01-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Shipped', 'Shipped'), ('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Received', 'Received')], max_length=100, null=True),
        ),
    ]
