# Generated by Django 4.0.1 on 2022-01-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Scheduled', 'Scheduled'), ('Shipped', 'Shipped'), ('Received', 'Received')], max_length=100, null=True),
        ),
    ]
